name = "Starlight"
author = "my-daarlin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "119e8beb35f1b5ad7e6186029cd434533186cc9d8160e325782015238b9786b0"

[versions]
fabric = "0.16.14"
minecraft = "1.21"
